[build]
  command = "cd frontend && npm install --include=dev && npm run build"
  publish = "frontend/dist"

[build.environment]
  NPM_FLAGS = "--include=dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"
